### ISSUE TITLE
No advantage, whereabouts can basically do itusage issue

### ISSUE THREAD

**Issue by BurlyLuo** [spidernet-io/spiderpool#1052]
**usage issue**
1. doubts about how to use the software

**Comment by iiiceoo** [comment]
@BurlyLuo First of all, the project is still under development, especially some guidance documents are missing. You can find some instructions [[here](https://spidernet-io.github.io/spiderpool/usage/basic/)](https://spidernet-io.github.io/spiderpool/usage/basic/). However, it should be noted that I haven't updated them for some time, so their contents may be relatively stale. Of course, I will update them recently so that more users like you can get help in this issue.

As for the advantages and disadvantages of [[whereabouts](https://github.com/k8snetworkplumbingwg/whereabouts)](https://github.com/k8snetworkplumbingwg/whereabouts) and spiderpool you mentioned, my answer is that you can regard spiderpool as an enhanced whereabouts with richer functions and more flexible configurations. Similarly, you can find relevant information in the official `usage` documents (may be relatively stale, too).

If you still have any questions in the subsequent use, please continue to comment on this issue, and I will reply to you, thank you.

**Comment by weizhoublue** [comment]
before the project , we have looked into kinds of IPAM and CNI project, including whereabouts,
We designed kinds of new features , such as static ip. you could refer to the usage doc for details
