### ISSUE TITLE
uninstall spiderpool plugin,old pool cannot be deleted

### ISSUE THREAD

**Issue by yulng** [spidernet-io/spiderpool#798]
1 install spiderpool plugin in demo-dev
2 create ip pool name is aaa
3 uninstall spiderpool plugin
4 kubectl get sp
5 ip pool aaa still exist
![image](https://user-images.githubusercontent.com/31728060/192955858-0fc778aa-0458-44c6-bc78-4fcd62fcbd75.png)

**Comment by iiiceoo** [comment]
Due to the existence of the **finalizer** of SpiderSubnet and SpiderIPPool resources, the CRDs and CRs related to Spiderpool cannot be properly uninstalled when `helm uninstall spiderpool` is executed. You can use `{SPIDERPOOL_PROJECT_ROOT}/tools/scripts/cleanCRD.sh` script to complete garbage cleaning.

The usage of this script will be supplemented to the spiderpool document later.

**Comment by yulng** [comment]
when DCE5.0 UI uninstall spiderpool ,also need to add this script

**Comment by yulng** [comment]
run cleanCRD.sh 报如图
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/31728060/195484637-6684c9e6-9aa3-438e-8ad4-dec0c2ace40e.png">
